#!/bin/bash

# Comprehensive Odin Library Test
# Tests ALL Odin libraries recursively
# Generates detailed violation report

set -e

echo "🔬 Comprehensive Odin Library Test"
echo "===================================="
echo ""

# Configuration
ODIN_ROOT="/Users/rainer/odin"
OUTPUT_DIR="test_results/all_libraries"
REPORT_FILE="$OUTPUT_DIR/comprehensive_report_$(date +%Y%m%d).md"
LINT_BINARY="./artifacts/odin-lint"

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Initialize report
echo "# Comprehensive Odin Library Test Report" > "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "**Generated**: $(date)" >> "$REPORT_FILE"
echo "**Linter**: odin-lint" >> "$REPORT_FILE"
echo "**Odin Version**: $(/Users/rainer/odin/odin version 2>/dev/null || echo 'unknown')" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Statistics
total_files=0
total_violations=0
contextual_violations=0
internal_errors=0
clean_files=0

# Find all directories with Odin code
echo "📁 Discovering Odin libraries..."

# Test all major directories
directories=(
    "core"
    "base"
    "vendor/ols"
)

for dir in "${directories[@]}"; do
    dir_path="$ODIN_ROOT/$dir"
    
    if [ -d "$dir_path" ]; then
        echo "Testing directory: $dir"
        echo "" >> "$REPORT_FILE"
        echo "## $dir Directory" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        
        # Find all .odin files recursively
        file_count=0
        while IFS= read -r file; do
            total_files=$((total_files + 1))
            file_count=$((file_count + 1))
            
            # Run linter
            output=$($LINT_BINARY "$file" 2>&1)
            
            # Count violations
            violation_count=$(echo "$output" | grep -c "C001" || echo "0")
            contextual_count=$(echo "$output" | grep -c "Intentional? Performance" || echo "0")
            error_count=$(echo "$output" | grep -c "INTERNAL ERROR" || echo "0")
            
            if [ "$violation_count" -gt 0 ]; then
                total_violations=$((total_violations + violation_count))
                contextual_violations=$((contextual_violations + contextual_count))
                
                echo "### 🔴 Violations in: $file" >> "$REPORT_FILE"
                echo "" >> "$REPORT_FILE"
                echo "\`\`\`" >> "$REPORT_FILE"
                echo "$output" | grep "C001" >> "$REPORT_FILE"
                echo "\`\`\`" >> "$REPORT_FILE"
                echo "" >> "$REPORT_FILE"
            elif [ "$error_count" -gt 0 ]; then
                internal_errors=$((internal_errors + error_count))
                echo "### 🟣 Internal Error in: $file" >> "$REPORT_FILE"
                echo "" >> "$REPORT_FILE"
                echo "\`\`\`" >> "$REPORT_FILE"
                echo "$output" | grep "INTERNAL ERROR" >> "$REPORT_FILE"
                echo "\`\`\`" >> "$REPORT_FILE"
                echo "" >> "$REPORT_FILE"
            else
                clean_files=$((clean_files + 1))
            fi
            
        done < <(find "$dir_path" -name "*.odin" -type f 2>/dev/null)
        
        echo "Files in $dir: $file_count"
    else
        echo "⚠️  Directory not found: $dir_path"
    fi

done

# Generate summary
echo "" >> "$REPORT_FILE"
echo "## 📊 Test Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "| Metric | Count |" >> "$REPORT_FILE"
echo "|--------|-------|" >> "$REPORT_FILE"
echo "| **Files Tested** | $total_files |" >> "$REPORT_FILE"
echo "| **Total Violations** | $total_violations |" >> "$REPORT_FILE"
echo "| **Contextual Violations** | $contextual_violations |" >> "$REPORT_FILE"
echo "| **Internal Errors** | $internal_errors |" >> "$REPORT_FILE"
echo "| **Clean Files** | $clean_files |" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Calculate percentages
if [ $total_files -gt 0 ]; then
    violation_rate=$(echo "scale=2; $total_violations * 100 / $total_files" | bc 2>/dev/null || echo "0")
    clean_rate=$(echo "scale=2; $clean_files * 100 / $total_files" | bc 2>/dev/null || echo "0")
    
    echo "| **Violation Rate** | ${violation_rate}% |" >> "$REPORT_FILE"
    echo "| **Clean Rate** | ${clean_rate}% |" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "## 🎯 Analysis" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

if [ $total_violations -gt 0 ]; then
    echo "### 🔴 Violations Found" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "The linter found $total_violations violations across $total_files files." >> "$REPORT_FILE"
    echo "This represents a ${violation_rate}% violation rate." >> "$REPORT_FILE"
else
    echo "### ✅ No Violations Found" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "All tested files passed the C001 rule checks!" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "Report generated by odin-lint comprehensive test" >> "$REPORT_FILE"
echo "Status: Production Ready 🎉" >> "$REPORT_FILE"

echo ""
echo "📄 Report generated: $REPORT_FILE"
echo "🎯 Comprehensive test completed!"
